services:
  db:
    image: postgres:18.0-alpine3.22
    ports:
      - '15432:5432'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-init.d:ro
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    command: ["postgres", "-c", "log_statement=all"]
