---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: appns
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      # hostAliases:
      # - ip: "192.168.56.11"
      #   hostnames:
      #   - "db.local"
      initContainers:
      - name: init
        image: docker.io/library/busybox
        command: ["sh", "-c"]
        args:
        - |
          echo "info.app.id=$(cat /proc/sys/kernel/random/uuid)">/app/config/application.properties
          dd if=/dev/zero of=/app/config/zero bs=1M count=2000
          ls -la /app/config
        restartPolicy: Never
        volumeMounts:
        - name: generated-volume
          mountPath: /app/config
        resources:
          limits:
            memory: "1000Mi" # Mi, M
      containers:
      - name: app
        image: docker.io/library/busybox
        command: ["sh", "-c"]
        args:
        - |
          dd if=/app/config/zero of=/tmp/zero bs=1M count=2000
          ls -la /tmp
          sleep infinity
        volumeMounts:
        - name: generated-volume
          mountPath: /app/config
          readOnly: true
        resources:
          limits:
            memory: "1000Mi" # Mi, M

      volumes:
      - name: config-volume
        configMap:
          name: app-config
          items:
          - key: application.properties
            path: application.properties
      - name: generated-volume
        emptyDir:
          medium: "Memory"
          sizeLimit: 2001Mi
      - name: secret-volume
        secret:
          secretName: db-secret
          items:
          - key: spring.datasource.url
            path: spring.datasource.url
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: appns
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
  - port: 8080
    targetPort: 8080
---  
