# kubectl -n appns create configmap app-config --from-file=application.properties=application.properties --dry-run=client -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: appns
data:
  application.properties: |-
    management.info.env.enabled=true
    info.app.instance-id=${random.uuid}