services:
  app:
    container_name: app
    image: registry.local:5000/library/app-boot:2.0.0
    ports:
      - '8080:8080'
    volumes:
      - ./application.properties:/app/application.properties:ro

